# Generated by Django 5.1.7 on 2025-03-21 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ivaclogininfo',
            name='cookies',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
