# Generated by Django 5.1.7 on 2025-03-21 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_app', '0002_ivaclogininfo_cookies'),
    ]

    operations = [
        migrations.AddField(
            model_name='ivaclogininfo',
            name='session_id',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
